// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Net.Data;

#nullable disable

namespace Server.Net.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Net.ActeurIntervenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("ActeursIntervenants");
                });

            modelBuilder.Entity("Server.Net.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Server.Net.AgentAnesthesique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dose")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("temps")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("AgentsAnesthesiques");
                });

            modelBuilder.Entity("Server.Net.AntecedentChirurgical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AntecedentsChirurgicaux");
                });

            modelBuilder.Entity("Server.Net.AntecedentMedical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeAntecedent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeAntecedentLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("AntecedentsMedicaux");
                });

            modelBuilder.Entity("Server.Net.AppNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Distination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTypeAssemblyQualifiedName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedUserIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotificationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserIds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("Server.Net.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnneeScolaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Children")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdUnite")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFakeDb")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Server.Net.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Server.Net.Arme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("Server.Net.BilanInOut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("BilanInOut");
                });

            modelBuilder.Entity("Server.Net.ConsigneAnesthesique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ConsignesAnesthesiques");
                });

            modelBuilder.Entity("Server.Net.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double?>("BMI")
                        .HasColumnType("REAL");

                    b.Property<string>("ConclusionExamin")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateInterventionPrevu")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionConsultation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MedecinId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Poids")
                        .HasColumnType("REAL");

                    b.Property<string>("PrevisionCG")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevisionPF")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevisionPlaquette")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("S_c")
                        .HasColumnType("REAL");

                    b.Property<double?>("Taille")
                        .HasColumnType("REAL");

                    b.Property<string>("TraitementAPoursuivre")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraitementActuel")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeAnesthesie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Urgence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateConsultation");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("Server.Net.DMSI_Antecedents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DMSI_Dossiers_MedicauxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DMSI_Dossiers_MedicauxId");

                    b.ToTable("DMSI_Antecedents");
                });

            modelBuilder.Entity("Server.Net.DMSI_Conduite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Atb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Atc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutreTrait")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClearanceCreat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DebitInsp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DialCritere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diurese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diuretique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dobutamine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echocardio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeuresDialyse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdDossier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeVentilatoire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nutrition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptimisationHd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PauseTeleinsp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanCardioAutre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanRespAutre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remplissage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rvs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sedation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapAi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapFiO2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapPente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapPep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapTiMax")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapTrigger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiBipapTriggerExp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiCpapDebitO2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVaciFio2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVaciFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVaciIe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVaciPep")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVaciVt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiVsDebitO2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ves")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdDossier")
                        .IsUnique();

                    b.ToTable("DMSI_Conduites");
                });

            modelBuilder.Entity("Server.Net.DMSI_Dossiers_Medicaux", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AvoirCovid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaractereUrgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdmission")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSortie")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoireDuMalade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MedecinId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeSortie")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotifAdmission")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonneAJoindreTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VaccinationCovid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DateAdmission");

                    b.HasIndex("MedecinId");

                    b.HasIndex("PatientId");

                    b.ToTable("DMSI_Dossiers_Medicaux");
                });

            modelBuilder.Entity("Server.Net.DMSI_Evolutions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Avis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DMSI_Dossiers_MedicauxId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Medecin_1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Medecin_2Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DMSI_Dossiers_MedicauxId");

                    b.HasIndex("Medecin_1Id");

                    b.HasIndex("Medecin_2Id");

                    b.ToTable("DMSI_Evolutions");
                });

            modelBuilder.Entity("Server.Net.DMSI_Examins_Cliniques", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Autres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evaluation_DN4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evaluation_EOC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evaluation_EVA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ex_Cardiovasculaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ex_Gastro_intestinal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ex_General")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ex_Neurologique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ex_Uro_Nephrologie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pleuro_Pulmonaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DossierId")
                        .IsUnique();

                    b.ToTable("DMSI_Examins_Cliniques");
                });

            modelBuilder.Entity("Server.Net.DMSI_Examins_Complementaires", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ALAT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ASAT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Albumine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CHOL_TTL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPK_MB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CRP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Clairance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Creatinine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("D_Dimeres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ECG")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Echographie_Cardiaque")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Electrophorese_Proteines")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ferritinemie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fibrinogene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GGT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GLY")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HBA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HCO3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HDL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("INR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("K")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LACTATES")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LDL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NT_Pro_BNP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Na")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PAL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PLQ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaCO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaO2_FiO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Radiographie_Thorax")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sintrom_Dose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TCK")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TG")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("T_Protides")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Troponine_T")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DossierId")
                        .IsUnique();

                    b.ToTable("DMSI_Examins_Complementaires");
                });

            modelBuilder.Entity("Server.Net.DMSI_Metrics_Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BMI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeficitMoteur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diurese")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DossierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FreqRes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OY")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poids")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pouls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pupilles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScoreGlasgow")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpO2SousO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpO2_SansO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Taille")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DossierId")
                        .IsUnique();

                    b.ToTable("DMSI_Metrics_Admission");
                });

            modelBuilder.Entity("Server.Net.DMSI_Traitements_Encours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DossierId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.ToTable("DMSI_Traitements_Encours");
                });

            modelBuilder.Entity("Server.Net.DeroulementOperatoire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AgentValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Air")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ApportsCG")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ApportsGluc")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ApportsPFC")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ApportsPlasm")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ApportsSale")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Diurese")
                        .HasColumnType("INTEGER");

                    b.Property<string>("F")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequenceCardiaque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HCO3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ht")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("N2O")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PCO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PH")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PressionArterielleMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PressionArterielleMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Saignement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sevo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Temperature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Temps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempsOperatoire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("V")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("DeroulementsOperatoire");
                });

            modelBuilder.Entity("Server.Net.ExaminClinique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeExamin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeExaminLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ExaminsCliniques");
                });

            modelBuilder.Entity("Server.Net.ExternalEntity", b =>
                {
                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Access_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Expires_in")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Refresh_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServerName");

                    b.ToTable("ExternalEntities");
                });

            modelBuilder.Entity("Server.Net.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Server.Net.GradeScientifique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GradesScientifiques");
                });

            modelBuilder.Entity("Server.Net.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Asa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutreIntubation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Circuit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double>("DureeAnesthesie")
                        .HasColumnType("REAL");

                    b.Property<double>("DureeIntervention")
                        .HasColumnType("REAL");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Intubation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MatChauf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitorageAutres")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MonitorageVoieArt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Respirateur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SGast")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("STemp")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SVesicale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeAnesthesie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Urgence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("Date");

                    b.HasIndex("PatientId");

                    b.HasIndex("Date", "Status");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("Server.Net.Medecin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeActuel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeScientifique")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationnalite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTel2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medecins");
                });

            modelBuilder.Entity("Server.Net.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresseAr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradeActuel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Groupage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LieuNaissance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationnalite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomMere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomMereAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NombreEnfant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroTel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTel2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Poids")
                        .HasColumnType("REAL");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomPere")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrenomPereAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SituationFamilliale")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Taille")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Server.Net.PostOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalogiqueReveil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antalogique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntiCoagulants")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Antibiotique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AutreReveil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Autres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bilan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsignsParticuliersReveil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateBilan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePrescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlaconBloc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RealPostop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SortieAutorise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surveillance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("PostsOperation");
                });

            modelBuilder.Entity("Server.Net.ProblemePreOperatoire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("ProblemesPreOperatoire");
                });

            modelBuilder.Entity("Server.Net.Respirateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Respirateurs");
                });

            modelBuilder.Entity("Server.Net.ResumeOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entretien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extubation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Induction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InterventionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Intubation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reveil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ventilation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InterventionId");

                    b.ToTable("ResumeOperation");
                });

            modelBuilder.Entity("Server.Net.Specialite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("Server.Net.TypeAnesthesie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Abreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TypesAnesthesies");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Server.Net.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Server.Net.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Net.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Server.Net.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.ActeurIntervenant", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("ActeursIntervenants")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.AgentAnesthesique", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("AgentsAnesthsesiques")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.AntecedentChirurgical", b =>
                {
                    b.HasOne("Server.Net.Patient", null)
                        .WithMany("AntecedentsChirurgicaux")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.AntecedentMedical", b =>
                {
                    b.HasOne("Server.Net.Patient", null)
                        .WithMany("AntecedentsMedicaux")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.BilanInOut", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("BilanInOut")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.ConsigneAnesthesique", b =>
                {
                    b.HasOne("Server.Net.Consultation", null)
                        .WithMany("ConsignesAnesthesiques")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.Consultation", b =>
                {
                    b.HasOne("Server.Net.Medecin", "Medecin")
                        .WithMany("Consultations")
                        .HasForeignKey("MedecinId");

                    b.HasOne("Server.Net.Patient", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Server.Net.DMSI_Antecedents", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithMany("Antecedents")
                        .HasForeignKey("DMSI_Dossiers_MedicauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DMSI_Conduite", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithOne("DMSI_Conduite")
                        .HasForeignKey("Server.Net.DMSI_Conduite", "IdDossier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DMSI_Dossiers_Medicaux", b =>
                {
                    b.HasOne("Server.Net.Medecin", "Medecin")
                        .WithMany()
                        .HasForeignKey("MedecinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Net.Patient", "Patients")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medecin");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Server.Net.DMSI_Evolutions", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithMany("Evolutions")
                        .HasForeignKey("DMSI_Dossiers_MedicauxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Net.Medecin", "Medecin_1")
                        .WithMany()
                        .HasForeignKey("Medecin_1Id");

                    b.HasOne("Server.Net.Medecin", "Medecin_2")
                        .WithMany()
                        .HasForeignKey("Medecin_2Id");

                    b.Navigation("Dossier");

                    b.Navigation("Medecin_1");

                    b.Navigation("Medecin_2");
                });

            modelBuilder.Entity("Server.Net.DMSI_Examins_Cliniques", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithOne("Examins_Cliniques")
                        .HasForeignKey("Server.Net.DMSI_Examins_Cliniques", "DossierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DMSI_Examins_Complementaires", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithOne("Examins_Complementaires")
                        .HasForeignKey("Server.Net.DMSI_Examins_Complementaires", "DossierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DMSI_Metrics_Admission", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithOne("A_Admission")
                        .HasForeignKey("Server.Net.DMSI_Metrics_Admission", "DossierId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DMSI_Traitements_Encours", b =>
                {
                    b.HasOne("Server.Net.DMSI_Dossiers_Medicaux", "Dossier")
                        .WithMany("Traitements")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("Server.Net.DeroulementOperatoire", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("OperationDetails")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.ExaminClinique", b =>
                {
                    b.HasOne("Server.Net.Consultation", null)
                        .WithMany("ExaminsCliniques")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.Intervention", b =>
                {
                    b.HasOne("Server.Net.Consultation", "Consultation")
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Net.Patient", null)
                        .WithMany("Interventions")
                        .HasForeignKey("PatientId");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Server.Net.PostOperation", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("PostOperation")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.ProblemePreOperatoire", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("ProblemesPreOperatoires")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.ResumeOperation", b =>
                {
                    b.HasOne("Server.Net.Intervention", null)
                        .WithMany("ResumeOperation")
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Net.Consultation", b =>
                {
                    b.Navigation("ConsignesAnesthesiques");

                    b.Navigation("ExaminsCliniques");
                });

            modelBuilder.Entity("Server.Net.DMSI_Dossiers_Medicaux", b =>
                {
                    b.Navigation("A_Admission");

                    b.Navigation("Antecedents");

                    b.Navigation("DMSI_Conduite");

                    b.Navigation("Evolutions");

                    b.Navigation("Examins_Cliniques");

                    b.Navigation("Examins_Complementaires");

                    b.Navigation("Traitements");
                });

            modelBuilder.Entity("Server.Net.Intervention", b =>
                {
                    b.Navigation("ActeursIntervenants");

                    b.Navigation("AgentsAnesthsesiques");

                    b.Navigation("BilanInOut");

                    b.Navigation("OperationDetails");

                    b.Navigation("PostOperation");

                    b.Navigation("ProblemesPreOperatoires");

                    b.Navigation("ResumeOperation");
                });

            modelBuilder.Entity("Server.Net.Medecin", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("Server.Net.Patient", b =>
                {
                    b.Navigation("AntecedentsChirurgicaux");

                    b.Navigation("AntecedentsMedicaux");

                    b.Navigation("Consultations");

                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
